# Generated by Django 5.1.2 on 2024-10-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
